import { test, expect, apiLogin } from '../fixtures/auth.js';
import { goOffline, goOnline, countRequests, blockStorage, warmServiceWorker } from '../fixtures/faults.js';

/**
 * JOURNEY 3 — PWA offline (a SUPPORTED client — NOT the field device).
 *
 * CORRECTION (per Matt): the inspector's field device is the native Expo app, not
 * the PWA. Playwright cannot reach the real offline field day — that lives in two
 * other layers, and this file must not pretend to own it:
 *
 *   Layer 1 — the shared law (syncCore / serviceOfNotice, generated by
 *     scripts/gen-shared-client-libs.js, SHA-pinned). The offline decision logic is
 *     ONE testable artifact; both clients render on top of it. The fault-injection
 *     cases — dead storage, forced 500, mid-save disconnect, "never lie about
 *     saving" — are proven ONCE here and hold for both clients. Cheapest, highest
 *     leverage. (So faults.js/blockStorage etc. are a PWA cross-check, not the
 *     canonical proof.)
 *   Layer 3 — the native iPad via Maestro + the manual iPad acceptance checklist.
 *     A genuine dead zone (airplane mode on real hardware) is NOT automatable by
 *     Maestro or Detox — the checklist is permanent, not a stopgap.
 *
 * What THIS file owns: the PWA as a supported browser client — that it installs a
 * service worker, degrades without blanking, and doesn't re-download storms.
 * The building-intel / on-device-notice cases below are the NATIVE field-device
 * behaviors, kept here only as PWA-client parity checks.
 */

test.describe('PWA offline (supported client)', () => {
  const OFFLINE_UNAVAILABLE =
    'PWA service worker did not take control in this automated context — offline behavior is ' +
    'verified on the installed iPad PWA instead (see the manual iPad acceptance checklist).';

  test('the PWA service worker takes control (so the app can run offline)', async ({ page, baseURL }) => {
    await apiLogin(page, 'officer', baseURL || '');
    await page.goto('/');
    await expect(page.getByPlaceholder(/1234/i)).toBeHidden({ timeout: 10_000 });
    const controlling = await warmServiceWorker(page);
    test.skip(!controlling, OFFLINE_UNAVAILABLE);
    expect(controlling, 'the PWA service worker should control the page after warm-up').toBeTruthy();
    // TODO(selector): also assert the day's on-device queue is populated (not the "inert, empty queue" bug).
  });

  test('going offline does not blank the app or crash it', async ({ page, context, baseURL }) => {
    await apiLogin(page, 'officer', baseURL || '');
    await page.goto('/');
    await expect(page.getByPlaceholder(/1234/i)).toBeHidden({ timeout: 10_000 });
    const controlling = await warmServiceWorker(page);   // the SW must control the page before offline works
    test.skip(!controlling, OFFLINE_UNAVAILABLE);
    await goOffline(context);
    await page.reload().catch(() => {});                 // PWA serves the shell from cache offline
    // The app shell must still render *something* — not a dead white page.
    await expect(page.locator('body')).not.toBeEmpty();
    await goOnline(context);
  });

  test('the same data is not re-downloaded many times per page load', async ({ page, baseURL }) => {
    await apiLogin(page, 'officer', baseURL || '');
    // Watch a representative operational endpoint; the report caught a 5×-per-load storm.
    const counter = await countRequests(page, '**/api/pre-plans**'); // TODO(path): confirm endpoint
    await page.goto('/');
    await page.waitForTimeout(1500);
    expect(counter.count, `pre-plans fetched ${counter.count}× on one load`).toBeLessThanOrEqual(1);
  });

  test.fixme('Size-Up shows building intel offline — never "no building" for "no signal"', async ({ page, context, baseURL }) => {
    await apiLogin(page, 'officer', baseURL || '');
    await page.goto('/');
    // TODO(selector): pre-load a property with a known pre-plan + hydrants while online.
    await goOffline(context);
    // TODO(selector): open Size-Up for that address during a (simulated) live call.
    // Assert: the pre-plan and hydrants render FROM the device, each showing its age;
    // out-of-service hydrants are flagged, not drawn live. Assert we NEVER show the
    // literal empty-state text "no pre-plan on file" / "no hydrants nearby" while offline
    // for an address that was cached.
  });

  test.fixme('a notice renders on the device with no connection', async ({ page, context, baseURL }) => {
    await apiLogin(page, 'officer', baseURL || '');
    await page.goto('/');
    await goOffline(context);
    // TODO(selector): walk a violation → cite → sign → generate the Notice of Violation.
    // Assert: the notice document is produced ON the device (not fetched), and a
    // save/share path exists that does not depend on the browser print dialog.
  });

  test.fixme('the app never claims saved when storage is dead', async ({ page, baseURL }) => {
    await blockStorage(page);            // storage throws before the app boots
    await apiLogin(page, 'officer', baseURL || '');
    await page.goto('/');
    // TODO(selector): make an edit that would "save" to the device.
    // Assert: the UI shows a FAILURE state — never "All changes saved" — and offers no
    // "recovered — clear it" action that could destroy work.
  });
});
