'use strict';
const { nfirsReports } = require('./db');

const FDID = '14-001';

const blank = () => ({
  fdid: FDID,
  incidentNumber: '',
  exposureNumber: '000',
  incidentDate: '',
  alarmTime: '',
  arrivalTime: '',
  controlledTime: '',
  clearedTime: '',
  incidentTypeCode: '',
  aidCode: 'N',
  streetNumber: '',
  streetPrefix: '',
  streetName: '',
  streetType: '',
  streetSuffix: '',
  aptSuite: '',
  city: 'Maplewood',
  state: 'MN',
  zip: '55117',
  crossStreet: '',
  propertyUseCode: '',
  action1: '',
  action2: '',
  action3: '',
  suppressionApparatus: 0,
  suppressionPersonnel: 0,
  emsApparatus: 0,
  emsPersonnel: 0,
  otherApparatus: 0,
  otherPersonnel: 0,
  civilianDeaths: 0,
  civilianInjuries: 0,
  fsDeaths: 0,
  fsInjuries: 0,
  propertyLoss: '',
  contentsLoss: '',
  isStructureFire: false,
  structureType: '',
  buildingStatus: '',
  storiesAboveGrade: '',
  storiesBelowGrade: '',
  mainFloorArea: '',
  fireOriginCode: '',
  fireCauseCode: '',
  contributingFactor1: '',
  contributingFactor2: '',
  humanFactors1: '',
  humanFactors2: '',
  detectorPresence: '',
  detectorOperation: '',
  detectorEffectiveness: '',
  detectorFailureReason: '',
  sprinklerPresence: '',
  sprinklerOperation: '',
  sprinklerFailureReason: '',
  status: 'Draft',
  narrativeStatement: '',
  preparedBy: '',
  officerInCharge: '',
  reviewedBy: '',
  linkedIncidentId: null,
});

module.exports = async function seedNfirs() {
  const existingReports = await nfirsReports.all(1);
  if (existingReports.length === 0) {
  const reports = [
    {
      ...blank(),
      incidentNumber: '26-0001',
      incidentDate: '2026-01-04',
      alarmTime: '02:17', arrivalTime: '02:24', controlledTime: '03:41', clearedTime: '04:55',
      incidentTypeCode: '111', aidCode: '4',
      streetNumber: '412', streetName: 'Elmwood', streetType: 'Dr',
      city: 'Maplewood', state: 'MN', zip: '55117',
      propertyUseCode: '419',
      action1: '11', action2: '52', action3: '12',
      suppressionApparatus: 4, suppressionPersonnel: 12,
      civilianInjuries: 0, civilianDeaths: 0, fsInjuries: 0, fsDeaths: 0,
      propertyLoss: '45000', contentsLoss: '12000',
      isStructureFire: true,
      structureType: '1', fireOriginCode: '09', fireCauseCode: '2',
      detectorPresence: '1', detectorOperation: '1', sprinklerPresence: 'N',
      status: 'Complete',
      narrativeStatement: 'Kitchen fire extended to wall cavity. Cause: unattended cooking. Mutual aid from Station 12.',
      preparedBy: 'Mike Harrington', officerInCharge: 'Maria Delgado',
      linkedIncidentId: 1,
    },
    {
      ...blank(),
      incidentNumber: '26-0002',
      incidentDate: '2026-01-09',
      alarmTime: '14:43', arrivalTime: '14:51', controlledTime: '15:20', clearedTime: '15:45',
      incidentTypeCode: '322', aidCode: 'N',
      streetName: 'Route 22 at Birch Hill Rd',
      city: 'Maplewood', state: 'MN', zip: '55117',
      propertyUseCode: '952',
      action1: '32', action2: '36', action3: '77',
      suppressionApparatus: 2, suppressionPersonnel: 6,
      emsApparatus: 1, emsPersonnel: 2,
      civilianInjuries: 2, civilianDeaths: 0,
      propertyLoss: '28000', contentsLoss: '0',
      status: 'Submitted',
      narrativeStatement: 'Two-vehicle MVA. Moderate injuries. Both patients transported to Maplewood General.',
      preparedBy: 'Nathan McGee', officerInCharge: 'Nathan McGee',
      linkedIncidentId: 2,
    },
    {
      ...blank(),
      incidentNumber: '26-0007',
      incidentDate: '2026-02-11',
      alarmTime: '03:22', arrivalTime: '03:29', controlledTime: '04:58', clearedTime: '06:15',
      incidentTypeCode: '111', aidCode: '4',
      streetNumber: '1847', streetName: 'Lakeview', streetType: 'Blvd',
      city: 'Maplewood', state: 'MN', zip: '55117',
      propertyUseCode: '429',
      action1: '11', action2: '52', action3: '21',
      suppressionApparatus: 5, suppressionPersonnel: 16,
      civilianInjuries: 1, civilianDeaths: 0, fsInjuries: 1, fsDeaths: 0,
      propertyLoss: '180000', contentsLoss: '55000',
      isStructureFire: true,
      structureType: '1', storiesAboveGrade: '3',
      fireOriginCode: '02', fireCauseCode: '1',
      detectorPresence: '1', detectorOperation: '2', sprinklerPresence: 'N',
      status: 'Draft',
      narrativeStatement: 'Third-floor apartment fire, suspected arson. One civilian with smoke inhalation transported. One FF minor burn injury.',
      preparedBy: 'Mike Harrington', officerInCharge: 'Sarah Chen',
      linkedIncidentId: 7,
    },
  ];
    for (const r of reports) { await nfirsReports.create(r, 1); }
    console.log(`[seed] Inserted ${reports.length} NFIRS reports`);
  }
};
