'use strict';
// sharedClientLibs.test.js — THE DRIFT ALARM (2026-07-13).
//
// The offline client cannot ask the server for the service-of-notice verdict — it
// has no signal. So it computes the Jones gate itself, from an ESM mirror of the
// server's pure module (generated by scripts/gen-shared-client-libs.js).
//
// If someone edits the server's gate logic and forgets to regenerate the mirror,
// the two drift — and the day they disagree, an inspector standing in a basement
// sees "SERVED" for a notice the server considers action_required. On a legal
// record that is not cosmetic.
//
// This test makes drift IMPOSSIBLE rather than merely unlikely: the suite goes red.

const { test } = require('node:test');
const assert = require('node:assert');
const { execFileSync } = require('node:child_process');
const path = require('node:path');
const fs = require('node:fs');

const ROOT = path.resolve(__dirname, '../../..');

test('shared client libs are in sync with their server source (no drift)', () => {
  try {
    execFileSync('node', [path.join(ROOT, 'scripts/gen-shared-client-libs.js'), '--check'],
      { cwd: ROOT, stdio: 'pipe' });
  } catch (e) {
    const out = `${e.stdout || ''}${e.stderr || ''}`;
    assert.fail(
      'A shared client module is STALE — the offline client would compute a different ' +
      'service-of-notice verdict than the server.\n' +
      'Fix: node scripts/gen-shared-client-libs.js\n\n' + out);
  }
});

test('the generated mirror actually exports the gate the client depends on', () => {
  const gen = fs.readFileSync(
    path.join(ROOT, 'client/src/lib/shared/serviceOfNotice.js'), 'utf8');
  for (const name of ['serviceStatus', 'jonesGate', 'isEffected', 'postingDefects',
                      'METHOD_LABELS', 'OUTCOME_LABELS']) {
    assert.ok(new RegExp(`\\b${name}\\b`).test(gen), `mirror must export ${name}`);
  }
  assert.match(gen, /GENERATED FILE — DO NOT EDIT/, 'mirror must warn against hand-editing');
  assert.match(gen, /source-sha256: [a-f0-9]{64}/, 'mirror must carry its source hash');
});

test('the inspection-result mirror exports the closed set the clients read (SC-1)', () => {
  // The result vocabulary is server-owned (constants/inspectionResult.js) and mirrored into
  // both clients so it can never drift again — the iPad once shipped 'Conditional', a result
  // that exists nowhere else and the server now rejects. This pins the mirror's surface.
  const gen = fs.readFileSync(
    path.join(ROOT, 'client/src/lib/shared/inspectionResult.js'), 'utf8');
  for (const name of ['RESULT_CODES', 'RESULT_LABELS', 'canonicalizeResult',
                      'isPassingResult', 'isUnmappableResult']) {
    assert.ok(new RegExp(`\\b${name}\\b`).test(gen), `result mirror must export ${name}`);
  }
  assert.match(gen, /GENERATED FILE — DO NOT EDIT/, 'mirror must warn against hand-editing');
  assert.match(gen, /source-sha256: [a-f0-9]{64}/, 'mirror must carry its source hash');
});
